// <auto-generated />
namespace SaundersRetail.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class madechangestosales : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(madechangestosales));
        
        string IMigrationMetadata.Id
        {
            get { return "202108231504301_made changes to sales"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
